# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: William M Volckmann II
#email: admin@cloud-cooking.org
description: > # this means to ignore newlines until "baseurl:"
  William M Volckmann II's TA page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wmvecon.firebaseapp.com/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: /:categories/:title/
# Build settings
markdown: kramdown
port: 3000 # change server port to 3000
timezone: America/Los_Angeles
gems:
  - jekyll-sitemap
